### ISSUE TITLE
Non ascii characters in the CORD19 dataset

### ISSUE THREAD

**Issue by Julie-Cowart** [ncbi-nlp/PubTator-Covid19#1]
All of the download files in the CORD19 dataset at https://ftp.ncbi.nlm.nih.gov/pub/lu/CORD19/ have non-ascii characters at the top of the file and multiple times throughout the file making them not valid json or xml files. For example, the first line of cord19-biocjson is

output.BioCXML.json/1.json0000644002575200123370001404626513652627621014424 0ustar  weic4iret{

In case this is temporary, the current date stamp of all files is 2020-05-15.

**Comment by rleaman** [comment]
The files were uploaded with the incorrect extension ".gz", they should be ".tar". The file extensions have been corrected on the site. After download, they need to be expanded with "tar -xvf" (or something equivalent) rather than gunzip. 
I have checked and that should fix the issue. Please report back whether that fixes the problem and I will close the issue at that time. Thanks!

**Comment by Julie-Cowart** [comment]
Yes that was the problem. Thanks!
